//! Stage 5 — self-contained HTML report.
//!
//! Dark-theme, inline CSS, no external assets. Built by direct string
//! concatenation — no templating engine, so the dependency surface stays
//! tiny and every variable interpolation is explicit (and therefore easy
//! to route through `html_escape`).
//!
//! Sections mirror HLD § Output format:
//!
//! 1. Header (banner badge + timestamp/version/branch/commit metadata).
//! 2. Category summary (CELT / SILK / Opus / DNN / Types / Coverage /
//!    Conformance).
//! 3. Phase summary (Unit Tests / Quality / Ambisonics / Bench).
//! 4. Module breakdown (`<crate>::<module>`).
//! 5. Failed tests (fully-qualified names).
//! 6. Coverage metrics (lines / functions / branches / regions).
//! 7. Benchmark table (Vector / Encode C / Encode Rust / Enc Ratio /
//!    Decode C / Decode Rust / Dec Ratio).
//!
//! XSS hygiene: every variable string is routed through `html_escape`, even
//! ones we think we control (commit SHA, branch name, version, test FQNs).

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

use crate::ambisonics::AmbisonicsResult;
use crate::banner::{BENCH_WARN_RATIO, Banner};
use crate::bench::{BenchResult, VectorBench};
use crate::cargo_parse::{Outcome as TestOutcomeKind, TestOutcome};
use crate::cli::Options;
use crate::fuzz::{Outcome as FuzzOutcome, Status as FuzzStatus};
use crate::ietf_vectors::{IetfVectorProvision, ProvisionStatus};
use crate::llvm_cov_parse::CoverageMetrics;
use crate::preflight::{AssetStatus, Outcome as PreflightOutcome};
use crate::quality::Outcome as QualityOutcome;
use crate::tests::Outcome as TestsOutcome;

/// All the inputs the renderer needs, bundled. Lifetime-borrowed from
/// `main.rs`'s stage outcomes — no heavy clones.
pub struct ReportContext<'a> {
    pub commit_sha: &'a str,
    pub branch: &'a str,
    pub version: &'a str,
    pub commit_subject: &'a str,
    pub timestamp: chrono::DateTime<chrono::Local>,
    pub banner: Banner,
    pub ietf_vectors: IetfVectorProvision,
    pub ietf_vectors_present: bool,
    pub preflight: PreflightOutcome,
    pub options: &'a Options,
    pub quality: &'a QualityOutcome,
    pub tests: &'a TestsOutcome,
    pub fuzz: &'a FuzzOutcome,
    pub ambisonics: &'a AmbisonicsResult,
    pub bench: &'a BenchResult,
}

/// Render the report into a self-contained HTML string. Pure — no I/O;
/// the caller writes the string to disk.
pub fn render(ctx: &ReportContext<'_>) -> String {
    let mut out = String::with_capacity(64 * 1024);

    out.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    out.push_str("<meta charset=\"utf-8\">\n");
    out.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
    out.push_str("<title>ropus Test Report</title>\n");
    // JSON array of `{label, enc, dec}` — parseable back with
    // `serde_json::from_str::<Vec<BenchRatio>>` so Phase 5's regression-vs-
    // previous-report logic is a one-liner. Embedded in a single-quoted
    // attribute so the JSON's double quotes pass through unescaped;
    // `html_escape` still runs to neutralise apostrophes and angle brackets
    // that could theoretically appear in a label.
    out.push_str(&format!(
        "<meta name=\"bench_ratios\" content='{}'>\n",
        html_escape(&bench_ratios_meta(&ctx.bench.vectors)),
    ));
    out.push_str("<style>\n");
    out.push_str(CSS);
    out.push_str("</style>\n</head>\n<body>\n<div class=\"container\">\n");

    render_header(&mut out, ctx);
    render_category_summary(&mut out, &ctx.tests.tests.per_test);
    render_phase_summary(&mut out, ctx);
    render_release_preflight(&mut out, &ctx.preflight);
    render_fuzz_sanity(&mut out, ctx.fuzz);
    render_module_breakdown(&mut out, &ctx.tests.tests.per_test);
    render_failed_tests(&mut out, &ctx.tests.tests.failed_test_names);
    render_coverage(&mut out, ctx);
    render_benchmarks(&mut out, &ctx.bench.vectors);

    out.push_str("<footer>Generated by <code>full-test</code> — ");
    out.push_str(env!("CARGO_PKG_NAME"));
    out.push(' ');
    out.push_str(env!("CARGO_PKG_VERSION"));
    out.push_str("</footer>\n");

    out.push_str("</div>\n</body>\n</html>\n");
    out
}

// ---------------------------------------------------------------------------
// CSS
// ---------------------------------------------------------------------------

/// Dark-theme stylesheet. Kept under 2 KiB per HLD guidance. Palette borrows
/// from mddosem's `src/bin/full_test.rs` (dark variables in the `@media
/// prefers-color-scheme: dark` block).
const CSS: &str = "\
:root { --bg:#0f172a; --fg:#e2e8f0; --card:#1e293b; --border:#334155; \
--meta:#94a3b8; --pass-bg:#064e3b; --pass-fg:#6ee7b7; --fail-bg:#7f1d1d; \
--fail-fg:#fca5a5; --warn-bg:#78350f; --warn-fg:#fde68a; --link:#60a5fa; \
--amber:#f59e0b; --green:#22c55e; }
* { box-sizing:border-box; }
body { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; \
background:var(--bg); color:var(--fg); margin:0; padding:20px; line-height:1.5; }
.container { max-width:1200px; margin:0 auto; }
h1 { margin:0 0 4px 0; font-size:1.6em; }
h2 { margin-top:28px; padding-bottom:6px; border-bottom:2px solid var(--border); font-size:1.2em; }
.meta { color:var(--meta); margin:0 0 20px 0; font-size:0.95em; }
.badge { display:inline-block; color:#fff; padding:3px 10px; border-radius:4px; \
font-size:0.8em; vertical-align:middle; margin-left:10px; }
table { width:100%; border-collapse:collapse; margin:10px 0 18px; font-size:0.92em; }
th,td { padding:6px 10px; text-align:left; border:1px solid var(--border); }
th { background:var(--card); font-weight:600; }
tr:nth-child(even) td { background:#17233b; }
.fail { background:var(--fail-bg); color:var(--fail-fg); font-weight:600; }
.pass { background:var(--pass-bg); color:var(--pass-fg); }
.warn { background:var(--warn-bg); color:var(--warn-fg); font-weight:600; }
.ratio-warn { color:var(--amber); font-weight:600; }
.ratio-fast { color:var(--green); font-weight:600; }
.num { text-align:right; font-variant-numeric:tabular-nums; }
ul.failed-tests { list-style:none; padding-left:0; margin:4px 0; }
ul.failed-tests li { font-family:'Consolas','Monaco',monospace; font-size:0.88em; \
padding:2px 6px; color:var(--fail-fg); }
.empty { color:var(--meta); font-style:italic; }
footer { margin-top:40px; padding-top:12px; border-top:1px solid var(--border); \
color:var(--meta); font-size:0.8em; text-align:center; }
";

// ---------------------------------------------------------------------------
// Sections
// ---------------------------------------------------------------------------

fn render_header(out: &mut String, ctx: &ReportContext<'_>) {
    debug_assert_eq!(ctx.ietf_vectors_present, ctx.ietf_vectors.available());
    let ts = ctx.timestamp.format("%Y-%m-%d %H:%M:%S").to_string();
    out.push_str(&format!(
        "<h1>ropus Test Report <span class=\"badge\" style=\"background:{color}\">{label}</span></h1>\n",
        color = ctx.banner.badge_color(),
        label = html_escape(ctx.banner.label()),
    ));
    out.push_str(&format!(
        "<p class=\"meta\">Generated: {ts} &bull; Version: {ver} &bull; Branch: {br} &bull; Commit: {sha} &mdash; {subj}</p>\n",
        ts = html_escape(&ts),
        ver = html_escape(ctx.version),
        br = html_escape(ctx.branch),
        sha = html_escape(ctx.commit_sha),
        subj = html_escape(ctx.commit_subject),
    ));

    // Note strip — IETF vectors + flag surface.
    let mut notes: Vec<String> = Vec::new();
    notes.push(ietf_vectors_note(&ctx.ietf_vectors));
    if ctx.options.quick {
        notes.push("Flag: <code>--quick</code> (quality + benchmarks skipped).".to_string());
    }
    if ctx.options.skip_quality {
        notes.push("Flag: <code>--skip-quality</code>.".to_string());
    }
    if ctx.options.skip_coverage {
        notes.push("Flag: <code>--skip-coverage</code>.".to_string());
    }
    if ctx.options.skip_benchmarks {
        notes.push("Flag: <code>--skip-benchmarks</code>.".to_string());
    }
    if ctx.options.skip_ambisonics {
        notes.push("Flag: <code>--skip-ambisonics</code>.".to_string());
    }
    if ctx.options.release_preflight {
        notes.push("Flag: <code>--release-preflight</code> (core profile).".to_string());
    }
    if !notes.is_empty() {
        out.push_str("<p class=\"meta\">");
        for (i, n) in notes.iter().enumerate() {
            if i > 0 {
                out.push_str(" &bull; ");
            }
            // Notes contain trusted literal HTML (`<code>…</code>`) above;
            // dynamic parts are escaped before they enter the note string.
            out.push_str(n);
        }
        out.push_str("</p>\n");
    }
}

fn render_release_preflight(out: &mut String, preflight: &PreflightOutcome) {
    out.push_str("<h2>Release preflight</h2>\n");
    let mode = if preflight.release_preflight {
        "active"
    } else {
        "report-only"
    };
    out.push_str(&format!(
        "<p class=\"meta\">Profile: <code>{}</code> &bull; Mode: {}</p>\n",
        html_escape(preflight.profile),
        html_escape(mode),
    ));
    out.push_str("<table>\n<tr><th>Asset</th><th>Key</th><th>Requirement</th><th>Status</th><th>Probe</th><th>Note</th></tr>\n");
    for asset in &preflight.assets {
        let cls = preflight_status_class(asset.status, asset.banner_blocking);
        let probes = if asset.probes.is_empty() {
            "derived".to_string()
        } else {
            asset
                .probes
                .iter()
                .map(|probe| html_escape(probe))
                .collect::<Vec<_>>()
                .join("<br>")
        };
        let note = asset.note.as_deref().unwrap_or("");
        out.push_str(&format!(
            "<tr><td>{}</td><td><code>{}</code></td><td>{}</td><td class=\"{}\">{}</td><td>{}</td><td>{}</td></tr>\n",
            html_escape(asset.label),
            html_escape(asset.key),
            html_escape(asset.requirement.as_str()),
            cls,
            html_escape(asset.status.as_str()),
            probes,
            html_escape(note),
        ));
    }
    out.push_str("</table>\n");
}

fn preflight_status_class(status: AssetStatus, banner_blocking: bool) -> &'static str {
    if banner_blocking {
        return "fail";
    }
    match status {
        AssetStatus::MissingRequired => "fail",
        AssetStatus::MissingOptional => "warn",
        AssetStatus::PresentRequired
        | AssetStatus::ProvisionedRequired
        | AssetStatus::PresentOptional => "pass",
    }
}

fn ietf_vectors_note(v: &IetfVectorProvision) -> String {
    match v.status {
        ProvisionStatus::Present => "IETF vectors: present.".to_string(),
        ProvisionStatus::Provisioned => {
            let script = script_note(v);
            format!("IETF vectors: provisioned during this run{script}.")
        }
        ProvisionStatus::Unavailable => {
            let script = script_note(v);
            let reason = v
                .reason
                .as_deref()
                .map(html_escape)
                .unwrap_or_else(|| "no diagnostic available".to_string());
            format!(
                "<span class=\"fail\">IETF vectors unavailable after provisioning</span>{script}: {reason}"
            )
        }
    }
}

fn script_note(v: &IetfVectorProvision) -> String {
    match &v.script {
        Some(path) => format!(" via <code>{}</code>", html_escape(&path.to_string_lossy())),
        None => String::new(),
    }
}

/// The conformance integration-test binary names. Each file under
/// `tests/conformance/tests/*.rs` compiles to its own binary, and cargo's
/// `test <name>` lines carry the file stem as the binary label — not the
/// crate name `conformance`. Confirmed against the directory listing
/// 2026-04-19: `{api, decode, encode, extensions, ietf_vectors, padding,
/// projection}`. Update alongside changes to `tests/conformance/tests/`.
const CONFORMANCE_BINARIES: &[&str] = &[
    "api",
    "decode",
    "encode",
    "extensions",
    "ietf_vectors",
    "padding",
    "projection",
];

/// Category summary — roll up `per_test` FQNs into top-level buckets.
/// Buckets match HLD § Output format: CELT / SILK / Opus / DNN / Types /
/// Coverage / Conformance, plus an `Other` row (rendered only when non-zero)
/// so no test is silently swallowed — every FQN either lands in a known
/// bucket or shows up as `Other`. The "Coverage" bucket here refers to
/// `coverage_tests::*` (extra coverage-focused tests), not the llvm-cov
/// metrics block — distinct sections.
fn render_category_summary(out: &mut String, per_test: &[TestOutcome]) {
    out.push_str("<h2>Category summary</h2>\n");
    if per_test.is_empty() {
        out.push_str("<p class=\"empty\">No test results (stage skipped or build failed).</p>\n");
        return;
    }
    let mut buckets: BTreeMap<&'static str, (u32, u32, u32)> = BTreeMap::new();
    for name in [
        "CELT",
        "SILK",
        "Opus",
        "DNN",
        "Types",
        "Coverage",
        "Conformance",
        "Other",
    ] {
        buckets.insert(name, (0, 0, 0));
    }
    for t in per_test {
        let cat = categorise_fqn(&t.fqn, &t.binary);
        if let Some(slot) = buckets.get_mut(cat) {
            slot.0 += 1;
            match t.outcome {
                TestOutcomeKind::Pass => slot.1 += 1,
                TestOutcomeKind::Fail => slot.2 += 1,
                TestOutcomeKind::Ignored => {}
            }
        }
    }
    out.push_str("<table>\n<tr><th>Category</th><th class=\"num\">Total</th><th class=\"num\">Passed</th><th class=\"num\">Failed</th></tr>\n");
    // Stable render order matches the HLD list (not alphabetical). `Other`
    // is appended last and suppressed when empty — no zero-count row for
    // the expected case.
    for cat in [
        "CELT",
        "SILK",
        "Opus",
        "DNN",
        "Types",
        "Coverage",
        "Conformance",
    ] {
        let (total, passed, failed) = buckets.get(cat).copied().unwrap_or((0, 0, 0));
        // Emit as a single combined class so the result is valid HTML
        // (browsers tolerate `class="a" class="b"` but HTML5 disallows it).
        let fail_cls = if failed > 0 { " fail" } else { "" };
        out.push_str(&format!(
            "<tr><td>{}</td><td class=\"num\">{}</td><td class=\"num\">{}</td><td class=\"num{}\">{}</td></tr>\n",
            html_escape(cat), total, passed, fail_cls, failed,
        ));
    }
    let (other_total, other_passed, other_failed) =
        buckets.get("Other").copied().unwrap_or((0, 0, 0));
    if other_total > 0 {
        let fail_cls = if other_failed > 0 { " fail" } else { "" };
        out.push_str(&format!(
            "<tr><td>Other</td><td class=\"num\">{}</td><td class=\"num\">{}</td><td class=\"num{}\">{}</td></tr>\n",
            other_total, other_passed, fail_cls, other_failed,
        ));
    }
    out.push_str("</table>\n");
}

/// Classify an FQN into one of the category buckets. The logic is:
///
/// 1. Tests whose binary is one of the known conformance integration-test
///    binaries (see `CONFORMANCE_BINARIES`) or whose FQN contains
///    `conformance::` land in the Conformance bucket.
/// 2. Otherwise look at the FQN head — `silk::`, `celt::`, `opus::`, `dnn::`,
///    `types::`.
/// 3. Tests starting `coverage_tests::` feed the "Coverage" bucket (these are
///    the deliberate coverage-padding tests inside ropus).
/// 4. Everything else falls back to "Other" so unexpected binaries
///    (`harness::`, future integration crates, lone-fn FQNs) surface as an
///    audit trail instead of polluting Types.
fn categorise_fqn(fqn: &str, binary: &str) -> &'static str {
    if binary == "conformance"
        || CONFORMANCE_BINARIES.contains(&binary)
        || fqn.contains("conformance::")
    {
        return "Conformance";
    }
    let head = fqn.split("::").next().unwrap_or(fqn);
    match head {
        "silk" => "SILK",
        "celt" => "CELT",
        "opus" => "Opus",
        "dnn" => "DNN",
        "types" => "Types",
        "coverage_tests" => "Coverage",
        _ => "Other",
    }
}

fn render_phase_summary(out: &mut String, ctx: &ReportContext<'_>) {
    out.push_str("<h2>Phase summary</h2>\n");
    out.push_str("<table>\n<tr><th>Phase</th><th class=\"num\">Total</th><th class=\"num\">Passed</th><th class=\"num\">Failed</th><th class=\"num\">Skipped</th><th class=\"num\">Duration</th></tr>\n");

    // Unit Tests
    let t = &ctx.tests.tests;
    let total = t.total_passed + t.total_failed + t.total_ignored;
    let fail_cls = if t.total_failed > 0 || t.build_failed {
        " fail"
    } else {
        ""
    };
    let tests_dur = if t.skipped {
        "skipped".to_string()
    } else {
        format_duration(t.duration_ms)
    };
    out.push_str(&format!(
        "<tr><td>Unit Tests</td><td class=\"num\">{total}</td><td class=\"num\">{passed}</td><td class=\"num{fail_cls}\">{failed}</td><td class=\"num\">{ignored}</td><td class=\"num\">{dur}</td></tr>\n",
        passed = t.total_passed,
        failed = if t.build_failed { "build-failed".to_string() } else { t.total_failed.to_string() },
        ignored = t.total_ignored,
        dur = html_escape(&tests_dur),
    ));

    // Quality
    let q = ctx.quality;
    let (q_total, q_passed, q_failed, q_dur_ms) = if q.skipped {
        (0u32, 0u32, 0u32, 0u64)
    } else {
        let total = q.checks.len() as u32;
        let passed = q.checks.iter().filter(|c| c.passed).count() as u32;
        let failed = total - passed;
        let dur_ms: u64 = q.checks.iter().map(|c| c.duration.as_millis() as u64).sum();
        (total, passed, failed, dur_ms)
    };
    let q_fail_cls = if q_failed > 0 { " fail" } else { "" };
    let q_dur_str = if q.skipped {
        "skipped".to_string()
    } else {
        format_duration(q_dur_ms)
    };
    out.push_str(&format!(
        "<tr><td>Quality</td><td class=\"num\">{q_total}</td><td class=\"num\">{q_passed}</td><td class=\"num{q_fail_cls}\">{q_failed}</td><td class=\"num\">{skipped}</td><td class=\"num\">{dur}</td></tr>\n",
        skipped = if q.skipped { 1 } else { 0 },
        dur = html_escape(&q_dur_str),
    ));

    // Ambisonics
    let a = ctx.ambisonics;
    let (a_total, a_passed, a_failed) = if a.skipped {
        (0u32, 0u32, 0u32)
    } else {
        let total = a.per_order.len() as u32;
        let passed = a.per_order.iter().filter(|o| o.passed).count() as u32;
        (total, passed, total - passed)
    };
    let a_failed_disp = if a.build_failed {
        "build-failed".to_string()
    } else {
        a_failed.to_string()
    };
    let a_fail_cls = if a_failed > 0 || a.build_failed {
        " fail"
    } else {
        ""
    };
    let a_dur_str = if a.skipped {
        "skipped".to_string()
    } else {
        format_duration(a.duration_ms)
    };
    out.push_str(&format!(
        "<tr><td>Ambisonics</td><td class=\"num\">{a_total}</td><td class=\"num\">{a_passed}</td><td class=\"num{a_fail_cls}\">{failed}</td><td class=\"num\">{skipped}</td><td class=\"num\">{dur}</td></tr>\n",
        failed = html_escape(&a_failed_disp),
        skipped = if a.skipped { 1 } else { 0 },
        dur = html_escape(&a_dur_str),
    ));

    // Bench (WARN-only stage; failed count is crashed-vector count)
    let b = ctx.bench;
    let (b_total, b_passed, b_crashed, b_skipped_rows) = if b.skipped {
        (0u32, 0u32, 0u32, 0u32)
    } else {
        let total = b.vectors.len() as u32;
        let crashed = b.vectors.iter().filter(|v| v.crashed).count() as u32;
        let skipped_rows = b.vectors.iter().filter(|v| v.skipped).count() as u32;
        let passed = total - crashed - skipped_rows;
        (total, passed, crashed, skipped_rows)
    };
    let b_dur_str = if b.skipped {
        "skipped".to_string()
    } else {
        format_duration(b.duration_ms)
    };
    let b_failed_cls = if b.build_failed || b_crashed > 0 {
        " warn"
    } else {
        ""
    };
    let b_failed_disp = if b.build_failed {
        "build-failed".to_string()
    } else {
        b_crashed.to_string()
    };
    out.push_str(&format!(
        "<tr><td>Bench</td><td class=\"num\">{b_total}</td><td class=\"num\">{b_passed}</td><td class=\"num{b_failed_cls}\">{failed}</td><td class=\"num\">{skipped}</td><td class=\"num\">{dur}</td></tr>\n",
        failed = html_escape(&b_failed_disp),
        skipped = if b.skipped { 1 } else { b_skipped_rows },
        dur = html_escape(&b_dur_str),
    ));

    // Fuzz sanity (policy-owned stage; default full-test leaves it not requested)
    let f = ctx.fuzz;
    let f_total = f.targets.len() as u32;
    let f_failed = if f.status == FuzzStatus::Fail { 1 } else { 0 };
    let f_passed = if f.status == FuzzStatus::Pass || f.status == FuzzStatus::Warn {
        f_total.saturating_sub(f_failed)
    } else {
        0
    };
    let f_skipped = if f.status == FuzzStatus::NotRequested {
        1
    } else {
        0
    };
    let f_fail_cls = match f.status {
        FuzzStatus::Fail => " fail",
        FuzzStatus::Warn => " warn",
        _ => "",
    };
    let f_failed_disp = match f.status {
        FuzzStatus::Fail => "failed".to_string(),
        FuzzStatus::Warn => "warn".to_string(),
        _ => f_failed.to_string(),
    };
    let f_dur = if f.status == FuzzStatus::NotRequested {
        "not requested".to_string()
    } else {
        format_duration(f.duration_ms)
    };
    out.push_str(&format!(
        "<tr><td>Fuzz sanity</td><td class=\"num\">{f_total}</td><td class=\"num\">{f_passed}</td><td class=\"num{f_fail_cls}\">{failed}</td><td class=\"num\">{f_skipped}</td><td class=\"num\">{dur}</td></tr>\n",
        failed = html_escape(&f_failed_disp),
        dur = html_escape(&f_dur),
    ));

    out.push_str("</table>\n");
}

fn render_fuzz_sanity(out: &mut String, fuzz: &FuzzOutcome) {
    out.push_str("<h2>Fuzz sanity</h2>\n");
    out.push_str(&format!(
        "<p class=\"meta\">Mode: <code>{}</code> &bull; Status: <span class=\"{}\">{}</span></p>\n",
        html_escape(fuzz.mode.as_str()),
        fuzz_status_class(fuzz.status),
        html_escape(fuzz.status.as_str()),
    ));
    if !fuzz.command.is_empty() {
        out.push_str(&format!(
            "<p class=\"meta\">Command: <code>{}</code></p>\n",
            html_escape(&fuzz.command.join(" ")),
        ));
    }
    if !fuzz.issues.is_empty() {
        out.push_str("<ul class=\"failed-tests\">\n");
        for issue in &fuzz.issues {
            out.push_str(&format!("  <li>{}</li>\n", html_escape(issue)));
        }
        out.push_str("</ul>\n");
    }
    if fuzz.targets.is_empty() {
        out.push_str("<p class=\"empty\">(no fuzz target rows)</p>\n");
        return;
    }
    out.push_str("<table>\n<tr><th>Target</th><th>Build</th><th class=\"num\">Crashes</th><th>Replay</th></tr>\n");
    for target in &fuzz.targets {
        let cls = if target.build == "fail" || target.replay == "fail" {
            "fail"
        } else if target.build == "not_checked" || target.replay == "not_checked" {
            "warn"
        } else {
            "pass"
        };
        out.push_str(&format!(
            "<tr><td><code>{}</code></td><td class=\"{}\">{}</td><td class=\"num\">{}</td><td class=\"{}\">{}</td></tr>\n",
            html_escape(&target.name),
            cls,
            html_escape(&target.build),
            target.crashes,
            cls,
            html_escape(&target.replay),
        ));
    }
    out.push_str("</table>\n");
}

fn fuzz_status_class(status: FuzzStatus) -> &'static str {
    match status {
        FuzzStatus::Fail => "fail",
        FuzzStatus::Warn => "warn",
        FuzzStatus::Pass => "pass",
        FuzzStatus::NotRequested => "empty",
    }
}

fn render_module_breakdown(out: &mut String, per_test: &[TestOutcome]) {
    out.push_str("<h2>Module breakdown</h2>\n");
    if per_test.is_empty() {
        out.push_str("<p class=\"empty\">No module breakdown available.</p>\n");
        return;
    }
    // Group by `<binary>::<module>` where module is the first two FQN
    // components that aren't `tests`. `silk::decoder::tests::test_foo` →
    // `ropus::silk::decoder`. For a lone `integration_foo::bar::test` we
    // fall back to `<binary>::<first_component>`.
    let mut modules: BTreeMap<String, (u32, u32, u32)> = BTreeMap::new();
    for t in per_test {
        let key = module_key(&t.fqn, &t.binary);
        let slot = modules.entry(key).or_insert((0, 0, 0));
        slot.0 += 1;
        match t.outcome {
            TestOutcomeKind::Pass => slot.1 += 1,
            TestOutcomeKind::Fail => slot.2 += 1,
            TestOutcomeKind::Ignored => {}
        }
    }
    out.push_str("<table>\n<tr><th>Module</th><th class=\"num\">Total</th><th class=\"num\">Passed</th><th class=\"num\">Failed</th></tr>\n");
    for (module, (total, passed, failed)) in &modules {
        let fail_cls = if *failed > 0 { " fail" } else { "" };
        out.push_str(&format!(
            "<tr><td>{}</td><td class=\"num\">{}</td><td class=\"num\">{}</td><td class=\"num{}\">{}</td></tr>\n",
            html_escape(module),
            total,
            passed,
            fail_cls,
            failed,
        ));
    }
    out.push_str("</table>\n");
}

/// Derive a `<crate>::<module>` key from an FQN + binary label. The FQN tail
/// (`::tests::test_foo`) is dropped so a single module with many tests rolls
/// up to one row. The binary prefix is preserved so tests under `ropus` and
/// `conformance` stay distinct even when the module path coincides. If the
/// FQN already leads with the binary name (e.g. `conformance::decode::…`
/// inside binary `conformance`), the duplicate prefix is dropped so the
/// rendered key doesn't double up.
fn module_key(fqn: &str, binary: &str) -> String {
    // Strip a leading `<binary>::` from the FQN so we don't render
    // `conformance::conformance::decode`. Skip the strip when it would
    // leave the FQN empty (i.e. the FQN *is* the binary name).
    let dup_prefix = format!("{binary}::");
    let fqn = fqn.strip_prefix(&dup_prefix).unwrap_or(fqn);
    let parts: Vec<&str> = fqn.split("::").collect();
    // Strip a trailing `tests` segment + the test function name. Examples:
    //   silk::decoder::tests::test_foo → silk::decoder
    //   celt::bands::test_beta         → celt::bands
    //   lone_fn                        → (fallback: use fqn unchanged)
    let module_parts: Vec<&str> = match parts.len() {
        0 | 1 => return format!("{binary}::{fqn}"),
        _ => {
            // Drop the final function-name segment, and an optional
            // penultimate `tests` segment.
            let mut end = parts.len() - 1;
            if end > 0 && parts[end - 1] == "tests" {
                end -= 1;
            }
            parts[..end].to_vec()
        }
    };
    if module_parts.is_empty() {
        format!("{binary}::{fqn}")
    } else {
        format!("{binary}::{}", module_parts.join("::"))
    }
}

fn render_failed_tests(out: &mut String, failed: &[String]) {
    out.push_str("<h2>Failed tests</h2>\n");
    if failed.is_empty() {
        out.push_str("<p class=\"empty\">(none)</p>\n");
        return;
    }
    out.push_str("<ul class=\"failed-tests\">\n");
    for name in failed {
        out.push_str(&format!("  <li>{}</li>\n", html_escape(name)));
    }
    out.push_str("</ul>\n");
}

fn render_coverage(out: &mut String, ctx: &ReportContext<'_>) {
    out.push_str("<h2>Coverage metrics</h2>\n");
    let coverage = match &ctx.tests.coverage {
        Some(c) => c,
        None => {
            let reason = ctx
                .tests
                .tests
                .coverage_skip_reason
                .as_deref()
                .unwrap_or("not captured");
            out.push_str(&format!(
                "<p class=\"empty\">(coverage unavailable &mdash; reason: {})</p>\n",
                html_escape(reason),
            ));
            return;
        }
    };
    out.push_str("<table>\n<tr><th>Scope</th><th>Lines</th><th>Functions</th><th>Branches</th><th>Regions</th></tr>\n");
    render_coverage_row(out, "ropus", &coverage.ropus);
    render_coverage_row(out, "workspace", &coverage.workspace);
    out.push_str("</table>\n");
}

fn render_coverage_row(out: &mut String, scope: &str, m: &CoverageMetrics) {
    out.push_str(&format!(
        "<tr><td>{}</td><td class=\"num\">{}</td><td class=\"num\">{}</td><td class=\"num\">{}</td><td class=\"num\">{}</td></tr>\n",
        html_escape(scope),
        html_escape(&cell_cov(m.lines_covered, m.lines_total)),
        html_escape(&cell_cov(m.functions_covered, m.functions_total)),
        html_escape(&cell_cov(m.branches_covered, m.branches_total)),
        html_escape(&cell_cov(m.regions_covered, m.regions_total)),
    ));
}

fn cell_cov(covered: u64, total: u64) -> String {
    if total == 0 {
        return "0 / 0 (n/a)".to_string();
    }
    let pct = (covered as f64) * 100.0 / (total as f64);
    format!("{covered} / {total} ({pct:.1}%)")
}

fn render_benchmarks(out: &mut String, vectors: &[VectorBench]) {
    out.push_str("<h2>Benchmark table</h2>\n");
    if vectors.is_empty() {
        out.push_str("<p class=\"empty\">(benchmarks skipped)</p>\n");
        return;
    }
    out.push_str("<table>\n<tr><th>Vector</th><th>Encode C</th><th>Encode Rust</th><th class=\"num\">Enc Ratio</th><th>Decode C</th><th>Decode Rust</th><th class=\"num\">Dec Ratio</th></tr>\n");
    for v in vectors {
        if v.skipped {
            out.push_str(&format!(
                "<tr><td>{}</td><td colspan=\"6\" class=\"empty\">{}</td></tr>\n",
                html_escape(&v.label),
                html_escape(v.skip_reason.as_deref().unwrap_or("missing fixture")),
            ));
            continue;
        }
        if v.crashed {
            out.push_str(&format!(
                "<tr><td>{}</td><td colspan=\"6\" class=\"warn\"><em>crashed: {}</em></td></tr>\n",
                html_escape(&v.label),
                html_escape(v.crash_reason.as_deref().unwrap_or("(no reason captured)")),
            ));
            continue;
        }
        out.push_str(&format!(
            "<tr><td>{}</td><td class=\"num\">{}</td><td class=\"num\">{}</td><td class=\"num{}\">{}</td><td class=\"num\">{}</td><td class=\"num\">{}</td><td class=\"num{}\">{}</td></tr>\n",
            html_escape(&v.label),
            html_escape(&cell_ms(v.c_encode_ms)),
            html_escape(&cell_ms(v.rust_encode_ms)),
            ratio_class(v.enc_ratio),
            html_escape(&cell_ratio(v.enc_ratio)),
            html_escape(&cell_ms(v.c_decode_ms)),
            html_escape(&cell_ms(v.rust_decode_ms)),
            ratio_class(v.dec_ratio),
            html_escape(&cell_ratio(v.dec_ratio)),
        ));
    }
    out.push_str("</table>\n");
}

fn cell_ms(v: Option<f64>) -> String {
    match v {
        Some(x) if x.is_finite() => format!("{x:.2} ms"),
        _ => "—".to_string(),
    }
}

fn cell_ratio(v: Option<f64>) -> String {
    match v {
        Some(x) if x.is_finite() => format!("{x:.3}x"),
        _ => "—".to_string(),
    }
}

/// Extra CSS class to append after `num` in a ratio cell. Amber above the
/// WARN threshold, green below 1.0x (Rust faster than C), no extra class
/// otherwise. Returned as a leading-space suffix so the caller can splice it
/// directly into `class="num{...}"` — emitting a second `class=` attribute
/// is invalid HTML and some browsers silently drop the later one.
fn ratio_class(r: Option<f64>) -> &'static str {
    match r {
        Some(x) if x.is_finite() && x > BENCH_WARN_RATIO => " ratio-warn",
        Some(x) if x.is_finite() && x < 1.0 => " ratio-fast",
        _ => "",
    }
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

/// HTML-escape the five characters that can break out of element bodies or
/// attribute values. The set is deliberately conservative — apostrophe is
/// escaped too because attribute values sometimes use single quotes.
pub fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

/// Format a duration in milliseconds as human-readable `Xs` or `Xm Ys`.
pub fn format_duration(ms: u64) -> String {
    let total_secs = ms / 1000;
    if total_secs < 60 {
        return format!("{total_secs}s");
    }
    let m = total_secs / 60;
    let s = total_secs % 60;
    format!("{m}m {s}s")
}

/// One entry in the `<meta name="bench_ratios">` JSON array. `enc` / `dec` are
/// `None` when the ratio was missing (skipped fixture, crashed run, NaN/inf);
/// serde emits these as JSON `null` so the reader distinguishes "absent" from
/// "zero" without needing a sentinel value.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct BenchRatio {
    pub label: String,
    pub enc: Option<f64>,
    pub dec: Option<f64>,
}

/// Serialise the current run's bench ratios as a JSON array that round-trips
/// through the `<meta name="bench_ratios">` tag so a future full-test run can
/// compute regression-vs-previous-report via `serde_json::from_str`. JSON
/// (rather than a homegrown `|`/`;` DSL) keeps label content lossless — a
/// label containing delimiter characters no longer collides.
fn bench_ratios_meta(vectors: &[VectorBench]) -> String {
    let rows: Vec<BenchRatio> = vectors
        .iter()
        .map(|v| BenchRatio {
            label: v.label.clone(),
            enc: v.enc_ratio.filter(|r| r.is_finite()),
            dec: v.dec_ratio.filter(|r| r.is_finite()),
        })
        .collect();
    // serde_json::to_string on a Vec<BenchRatio> cannot fail — the types are
    // all primitives/strings. Fall back to `[]` if somehow it does, rather
    // than poisoning the HTML.
    serde_json::to_string(&rows).unwrap_or_else(|_| "[]".to_string())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ambisonics::{AmbisonicsResult, OrderOutcome};
    use crate::banner::Banner;
    use crate::bench::{BenchResult, VectorBench};
    use crate::cargo_parse::{BinaryResult, Outcome as OutcomeKind, TestOutcome, TestsResult};
    use crate::cli::Options;
    use crate::llvm_cov_parse::{CoverageMetrics, CoverageResult};
    use crate::quality::{Check, Outcome as QualityOutcome};
    use crate::tests::Outcome as TestsOutcome;
    use std::time::Duration;

    fn now() -> chrono::DateTime<chrono::Local> {
        chrono::Local::now()
    }

    fn test_outcome(fqn: &str, outcome: OutcomeKind, binary: &str) -> TestOutcome {
        TestOutcome {
            fqn: fqn.to_string(),
            outcome,
            binary: binary.to_string(),
        }
    }

    fn populated_tests() -> TestsOutcome {
        let t = TestsResult {
            duration_ms: 125_000,
            total_passed: 4,
            total_failed: 1,
            total_ignored: 1,
            per_test: vec![
                test_outcome(
                    "silk::decoder::tests::test_alpha",
                    OutcomeKind::Pass,
                    "ropus",
                ),
                test_outcome(
                    "silk::decoder::tests::test_beta",
                    OutcomeKind::Fail,
                    "ropus",
                ),
                test_outcome("celt::bands::tests::test_gamma", OutcomeKind::Pass, "ropus"),
                test_outcome(
                    "opus::encoder::tests::test_delta",
                    OutcomeKind::Pass,
                    "ropus",
                ),
                test_outcome(
                    "dnn::lpcnet::tests::test_epsilon",
                    OutcomeKind::Pass,
                    "ropus",
                ),
                test_outcome("coverage_tests::noop", OutcomeKind::Ignored, "ropus"),
                test_outcome(
                    "conformance::decode::test_zeta",
                    OutcomeKind::Pass,
                    "conformance",
                ),
            ],
            failed_test_names: vec!["silk::decoder::tests::test_beta".to_string()],
            binaries: vec![BinaryResult {
                name: "ropus".to_string(),
                passed: 4,
                failed: 1,
                ignored: 1,
                duration_ms: 120_000,
            }],
            ..TestsResult::default()
        };
        let coverage = CoverageResult {
            ropus: CoverageMetrics {
                lines_covered: 1000,
                lines_total: 1200,
                functions_covered: 200,
                functions_total: 220,
                branches_covered: 500,
                branches_total: 600,
                regions_covered: 1800,
                regions_total: 2000,
            },
            workspace: CoverageMetrics {
                lines_covered: 1500,
                lines_total: 1800,
                ..CoverageMetrics::default()
            },
        };
        TestsOutcome {
            tests: t,
            coverage: Some(coverage),
            coverage_skipped: false,
        }
    }

    fn quality_ok() -> QualityOutcome {
        QualityOutcome {
            skipped: false,
            checks: vec![
                Check {
                    name: "fmt",
                    passed: true,
                    duration: Duration::from_millis(1_200),
                    issues: Vec::new(),
                },
                Check {
                    name: "clippy",
                    passed: true,
                    duration: Duration::from_millis(58_000),
                    issues: Vec::new(),
                },
            ],
        }
    }

    fn ambisonics_ok() -> AmbisonicsResult {
        AmbisonicsResult {
            skipped: false,
            skip_reason: None,
            build_failed: false,
            duration_ms: 15_000,
            overall_pass: true,
            per_order: (1u8..=3u8)
                .map(|o| OrderOutcome {
                    order: o,
                    passed: true,
                    detail: "ok".to_string(),
                })
                .collect(),
        }
    }

    fn bench_ok() -> BenchResult {
        BenchResult {
            skipped: false,
            skip_reason: None,
            build_failed: false,
            duration_ms: 180_000,
            vectors: vec![
                VectorBench {
                    label: "SILK NB 8k mono noise".to_string(),
                    bitrate: 16_000,
                    skipped: false,
                    skip_reason: None,
                    crashed: false,
                    crash_reason: None,
                    c_encode_ms: Some(100.0),
                    rust_encode_ms: Some(85.0),
                    enc_ratio: Some(0.85),
                    c_decode_ms: Some(20.0),
                    rust_decode_ms: Some(22.0),
                    dec_ratio: Some(1.10),
                },
                VectorBench {
                    label: "MUSIC 48k stereo".to_string(),
                    bitrate: 128_000,
                    skipped: true,
                    skip_reason: Some("fixture missing at tests/vectors/music.wav".to_string()),
                    crashed: false,
                    crash_reason: None,
                    c_encode_ms: None,
                    rust_encode_ms: None,
                    enc_ratio: None,
                    c_decode_ms: None,
                    rust_decode_ms: None,
                    dec_ratio: None,
                },
            ],
        }
    }

    fn ctx<'a>(
        banner: Banner,
        options: &'a Options,
        quality: &'a QualityOutcome,
        tests: &'a TestsOutcome,
        amb: &'a AmbisonicsResult,
        bench: &'a BenchResult,
    ) -> ReportContext<'a> {
        let fuzz = Box::leak(Box::new(crate::fuzz::Outcome::not_requested()));
        ReportContext {
            commit_sha: "dd3fb17",
            branch: "main",
            version: "0.9.0",
            commit_subject: "fix(silk): clamp pitch_out",
            timestamp: now(),
            banner,
            ietf_vectors: IetfVectorProvision::present(),
            ietf_vectors_present: true,
            preflight: crate::preflight::Outcome::inactive(&IetfVectorProvision::present()),
            options,
            quality,
            tests,
            fuzz,
            ambisonics: amb,
            bench,
        }
    }

    #[test]
    fn render_produces_doctype_and_all_sections() {
        let opts = Options::default();
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = bench_ok();
        let c = ctx(Banner::Fail, &opts, &q, &t, &a, &b);
        let html = render(&c);
        assert!(html.starts_with("<!DOCTYPE html>\n<html lang=\"en\">"));
        assert!(html.contains("</html>"));
        // Every section header present.
        for heading in [
            "ropus Test Report",
            "Category summary",
            "Phase summary",
            "Release preflight",
            "Fuzz sanity",
            "Module breakdown",
            "Failed tests",
            "Coverage metrics",
            "Benchmark table",
        ] {
            assert!(
                html.contains(heading),
                "missing heading {heading:?} in render output"
            );
        }
    }

    #[test]
    fn release_preflight_table_renders_asset_contract() {
        let opts = Options {
            release_preflight: true,
            ..Options::default()
        };
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = bench_ok();
        let tmp = tempfile::tempdir().expect("tempdir");
        let preflight =
            crate::preflight::capture(tmp.path(), true, &IetfVectorProvision::present());
        let c = ReportContext {
            commit_sha: "abc",
            branch: "main",
            version: "0.9.0",
            commit_subject: "subj",
            timestamp: now(),
            banner: Banner::Fail,
            ietf_vectors: IetfVectorProvision::present(),
            ietf_vectors_present: true,
            preflight,
            options: &opts,
            quality: &q,
            tests: &t,
            fuzz: Box::leak(Box::new(crate::fuzz::Outcome::not_requested())),
            ambisonics: &a,
            bench: &b,
        };
        let html = render(&c);

        assert!(html.contains("Profile: <code>core</code>"));
        assert!(html.contains("Mode: active"));
        assert!(html.contains("<code>--release-preflight</code> (core profile)"));
        assert!(html.contains("<code>fixed_reference</code>"));
        assert!(html.contains("<code>conformance_sources</code>"));
        assert!(html.contains("<code>ietf_vectors</code>"));
        assert!(html.contains("<code>dnn_base_weights</code>"));
        assert!(html.contains("<code>dred_rdovae_weights</code>"));
        assert!(html.contains("<code>float_deep_plc_assets</code>"));
        assert!(html.contains("class=\"fail\">missing_required"));
        assert!(html.contains("class=\"pass\">present_required"));
        assert!(html.contains("class=\"warn\">missing_optional"));
        assert!(html.contains("failure accounting remains in Stage 2"));
    }

    #[test]
    fn banner_class_and_color_rendered() {
        let opts = Options::default();
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = bench_ok();
        for banner in [Banner::Pass, Banner::Fail, Banner::Warn] {
            let c = ctx(banner, &opts, &q, &t, &a, &b);
            let html = render(&c);
            assert!(
                html.contains(&format!(">{}</span>", banner.label())),
                "banner {banner:?} label not rendered in badge",
            );
            assert!(
                html.contains(banner.badge_color()),
                "banner {banner:?} color not rendered",
            );
        }
    }

    #[test]
    fn metadata_values_escaped() {
        // Feed a malicious commit subject and branch; they must appear
        // escaped, not as live markup.
        let opts = Options::default();
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = bench_ok();
        let c = ReportContext {
            commit_sha: "<deadbeef>",
            branch: "feature/<script>alert(1)</script>",
            version: "0.9.0",
            commit_subject: "\"pwn\" & rm -rf /",
            timestamp: now(),
            banner: Banner::Pass,
            ietf_vectors: IetfVectorProvision::present(),
            ietf_vectors_present: true,
            preflight: crate::preflight::Outcome::inactive(&IetfVectorProvision::present()),
            options: &opts,
            quality: &q,
            tests: &t,
            fuzz: Box::leak(Box::new(crate::fuzz::Outcome::not_requested())),
            ambisonics: &a,
            bench: &b,
        };
        let html = render(&c);
        assert!(
            !html.contains("<script>alert(1)</script>"),
            "unescaped <script> leaked into render output",
        );
        assert!(html.contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
        assert!(html.contains("&lt;deadbeef&gt;"));
        assert!(html.contains("&quot;pwn&quot; &amp; rm -rf /"));
    }

    #[test]
    fn failed_test_names_escaped() {
        let opts = Options::default();
        let q = quality_ok();
        let mut t = populated_tests();
        t.tests.failed_test_names = vec!["<img src=x onerror=alert(1)>".to_string()];
        let a = ambisonics_ok();
        let b = bench_ok();
        let c = ctx(Banner::Fail, &opts, &q, &t, &a, &b);
        let html = render(&c);
        assert!(!html.contains("<img src=x onerror=alert(1)>"));
        assert!(html.contains("&lt;img src=x onerror=alert(1)&gt;"));
    }

    #[test]
    fn bench_row_ratio_class_reflects_threshold() {
        // enc_ratio = 1.20 → warn; dec_ratio = 0.80 → fast.
        let opts = Options::default();
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = BenchResult {
            skipped: false,
            skip_reason: None,
            build_failed: false,
            duration_ms: 100,
            vectors: vec![VectorBench {
                label: "X".to_string(),
                bitrate: 64_000,
                skipped: false,
                skip_reason: None,
                crashed: false,
                crash_reason: None,
                c_encode_ms: Some(100.0),
                rust_encode_ms: Some(120.0),
                enc_ratio: Some(1.20),
                c_decode_ms: Some(100.0),
                rust_decode_ms: Some(80.0),
                dec_ratio: Some(0.80),
            }],
        };
        let c = ctx(Banner::Warn, &opts, &q, &t, &a, &b);
        let html = render(&c);
        assert!(html.contains("ratio-warn"));
        assert!(html.contains("ratio-fast"));
    }

    #[test]
    fn skipped_vector_collapses_to_single_cell_with_reason() {
        let opts = Options::default();
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = BenchResult {
            skipped: false,
            skip_reason: None,
            build_failed: false,
            duration_ms: 100,
            vectors: vec![VectorBench {
                label: "Missing".to_string(),
                bitrate: 64_000,
                skipped: true,
                skip_reason: Some("fixture missing at path/x.wav".to_string()),
                crashed: false,
                crash_reason: None,
                c_encode_ms: None,
                rust_encode_ms: None,
                enc_ratio: None,
                c_decode_ms: None,
                rust_decode_ms: None,
                dec_ratio: None,
            }],
        };
        let c = ctx(Banner::Pass, &opts, &q, &t, &a, &b);
        let html = render(&c);
        assert!(html.contains("fixture missing at path/x.wav"));
        assert!(html.contains("colspan=\"6\""));
    }

    #[test]
    fn crashed_vector_shows_reason_italicised() {
        let opts = Options::default();
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = BenchResult {
            skipped: false,
            skip_reason: None,
            build_failed: false,
            duration_ms: 100,
            vectors: vec![VectorBench {
                label: "Boom".to_string(),
                bitrate: 64_000,
                skipped: false,
                skip_reason: None,
                crashed: true,
                crash_reason: Some("ropus-compare exited 1".to_string()),
                c_encode_ms: None,
                rust_encode_ms: None,
                enc_ratio: None,
                c_decode_ms: None,
                rust_decode_ms: None,
                dec_ratio: None,
            }],
        };
        let c = ctx(Banner::Warn, &opts, &q, &t, &a, &b);
        let html = render(&c);
        assert!(html.contains("<em>crashed: ropus-compare exited 1</em>"));
    }

    #[test]
    fn coverage_unavailable_when_none() {
        let opts = Options::default();
        let q = quality_ok();
        let t = TestsOutcome {
            tests: TestsResult {
                coverage_skip_reason: Some("--skip-coverage passed".to_string()),
                ..TestsResult::default()
            },
            coverage: None,
            coverage_skipped: true,
        };
        let a = ambisonics_ok();
        let b = bench_ok();
        let c = ctx(Banner::Pass, &opts, &q, &t, &a, &b);
        let html = render(&c);
        assert!(html.contains("coverage unavailable"));
        assert!(html.contains("--skip-coverage passed"));
    }

    #[test]
    fn coverage_cells_render_with_percent() {
        let opts = Options::default();
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = bench_ok();
        let c = ctx(Banner::Pass, &opts, &q, &t, &a, &b);
        let html = render(&c);
        // 1000 / 1200 = 83.3%
        assert!(html.contains("1000 / 1200 (83.3%)"));
        // 0 / 0 (n/a) for the workspace zero-counter fields
        assert!(html.contains("0 / 0 (n/a)"));
    }

    #[test]
    fn empty_state_renders_without_panic() {
        // All stages skipped, no test data. The report still produces a
        // self-contained document with every section visible.
        let opts = Options {
            quick: true,
            skip_ambisonics: true,
            ..Options::default()
        };
        let q = QualityOutcome::skipped();
        let t = TestsOutcome {
            tests: TestsResult {
                skipped: true,
                skip_reason: Some("no run".to_string()),
                ..TestsResult::default()
            },
            coverage: None,
            coverage_skipped: true,
        };
        let a = AmbisonicsResult::skipped("--skip-ambisonics");
        let b = BenchResult::skipped("--quick");
        let c = ctx(Banner::Pass, &opts, &q, &t, &a, &b);
        let html = render(&c);
        assert!(html.contains("No test results"));
        assert!(html.contains("No module breakdown"));
        assert!(html.contains("(none)"));
        assert!(html.contains("coverage unavailable"));
        assert!(html.contains("benchmarks skipped"));
    }

    #[test]
    fn categorise_fqn_buckets_expected_heads() {
        assert_eq!(categorise_fqn("silk::decoder::tests::t", "ropus"), "SILK");
        assert_eq!(categorise_fqn("celt::bands::tests::t", "ropus"), "CELT");
        assert_eq!(categorise_fqn("opus::encoder::t", "ropus"), "Opus");
        assert_eq!(categorise_fqn("dnn::lpcnet::t", "ropus"), "DNN");
        assert_eq!(categorise_fqn("types::q16::t", "ropus"), "Types");
        assert_eq!(categorise_fqn("coverage_tests::basic", "ropus"), "Coverage");
        assert_eq!(
            categorise_fqn("anything::goes", "conformance"),
            "Conformance"
        );
        // Binary "unknown" with a conformance FQN prefix still routes.
        assert_eq!(
            categorise_fqn("conformance::decode::t", "unknown"),
            "Conformance"
        );
    }

    #[test]
    fn categorise_fqn_real_conformance_binary_names_route_to_conformance() {
        // Every *.rs under `tests/conformance/tests/` compiles to its own
        // binary. Confirmed by directory listing 2026-04-19:
        //   api, decode, encode, extensions, ietf_vectors, padding, projection
        // Inside those binaries, FQNs are flat (`testvector01_mono`,
        // `decode_null_error`, etc.) — no `conformance::` prefix appears.
        // Fixtures mirror real cargo output.
        assert_eq!(
            categorise_fqn("testvector01_mono", "ietf_vectors"),
            "Conformance"
        );
        assert_eq!(categorise_fqn("decode_null_error", "api"), "Conformance");
        assert_eq!(categorise_fqn("decode_silence", "decode"), "Conformance");
        assert_eq!(categorise_fqn("encode_roundtrip", "encode"), "Conformance");
        assert_eq!(
            categorise_fqn("dtx_flag_round_trips", "extensions"),
            "Conformance"
        );
        assert_eq!(categorise_fqn("padding_probe", "padding"), "Conformance");
        assert_eq!(
            categorise_fqn("projection_third_order", "projection"),
            "Conformance"
        );
    }

    #[test]
    fn categorise_fqn_unknown_binary_lands_in_other_not_types() {
        // A future integration-test binary (e.g. `harness`, `ropus-fb2k`) or
        // a lone-fn FQN shouldn't silently pollute Types — it should surface
        // as Other so the auditor can spot it.
        assert_eq!(categorise_fqn("lone_fn", "harness"), "Other");
        assert_eq!(categorise_fqn("check_something", "ropus-fb2k"), "Other");
        assert_eq!(categorise_fqn("bare_fn", "ropus"), "Other");
    }

    #[test]
    fn category_summary_other_row_only_when_nonzero() {
        // When the test set contains an unknown-binary FQN it shows up as
        // an Other row; when it doesn't, the Other row is elided entirely.
        let with_other = vec![
            test_outcome("lone_fn", OutcomeKind::Pass, "harness"),
            test_outcome("silk::x::tests::t", OutcomeKind::Pass, "ropus"),
        ];
        let mut html = String::new();
        render_category_summary(&mut html, &with_other);
        assert!(html.contains("<td>Other</td>"));

        let without_other = vec![test_outcome(
            "silk::x::tests::t",
            OutcomeKind::Pass,
            "ropus",
        )];
        let mut html = String::new();
        render_category_summary(&mut html, &without_other);
        assert!(!html.contains("<td>Other</td>"));
    }

    #[test]
    fn module_key_drops_trailing_tests_and_fn() {
        assert_eq!(
            module_key("silk::decoder::tests::test_alpha", "ropus"),
            "ropus::silk::decoder"
        );
        assert_eq!(
            module_key("celt::bands::test_beta", "ropus"),
            "ropus::celt::bands"
        );
        assert_eq!(module_key("lone_fn", "ropus"), "ropus::lone_fn");
    }

    #[test]
    fn module_key_strips_duplicate_binary_prefix() {
        // When the FQN already leads with the binary name — e.g. cargo
        // labels a conformance binary `conformance` and the FQN reads
        // `conformance::decode::test_zeta` — the rendered key would
        // otherwise double up as `conformance::conformance::decode`.
        assert_eq!(
            module_key("conformance::decode::test_zeta", "conformance"),
            "conformance::decode"
        );
        // No strip when the prefix doesn't match.
        assert_eq!(
            module_key("conformance::decode::test_zeta", "ropus"),
            "ropus::conformance::decode"
        );
        // Flat FQN whose only segment equals the binary — no strip; the
        // fallback preserves the binary as its own key.
        assert_eq!(
            module_key("conformance", "conformance"),
            "conformance::conformance"
        );
    }

    #[test]
    fn format_duration_human_shape() {
        assert_eq!(format_duration(0), "0s");
        assert_eq!(format_duration(999), "0s");
        assert_eq!(format_duration(1_000), "1s");
        assert_eq!(format_duration(59_999), "59s");
        assert_eq!(format_duration(60_000), "1m 0s");
        assert_eq!(format_duration(125_000), "2m 5s");
        assert_eq!(format_duration(3_600_000), "60m 0s");
    }

    #[test]
    fn html_escape_covers_five_chars() {
        assert_eq!(
            html_escape("<a href=\"x\">'it&that'</a>"),
            "&lt;a href=&quot;x&quot;&gt;&#39;it&amp;that&#39;&lt;/a&gt;"
        );
    }

    #[test]
    fn meta_bench_ratios_roundtrip_via_serde_json() {
        // The `<meta name="bench_ratios">` tag is how a future run can read
        // the previous ratios for regression comparison. We serialise as
        // JSON and assert a serialize → parse → equal round-trip so the
        // regression reader (Phase 5 follow-up) is a one-liner.
        let vectors = vec![
            VectorBench {
                label: "A".to_string(),
                bitrate: 64_000,
                skipped: false,
                skip_reason: None,
                crashed: false,
                crash_reason: None,
                c_encode_ms: Some(100.0),
                rust_encode_ms: Some(85.0),
                enc_ratio: Some(0.85),
                c_decode_ms: Some(20.0),
                rust_decode_ms: Some(22.0),
                dec_ratio: Some(1.1),
            },
            VectorBench {
                // Delimiter characters that would have collided with the
                // old `|`/`;` DSL; JSON preserves them verbatim.
                label: "B;|escape".to_string(),
                bitrate: 128_000,
                skipped: true,
                skip_reason: Some("fixture missing".to_string()),
                crashed: false,
                crash_reason: None,
                c_encode_ms: None,
                rust_encode_ms: None,
                enc_ratio: None,
                c_decode_ms: None,
                rust_decode_ms: None,
                dec_ratio: None,
            },
        ];
        let meta = bench_ratios_meta(&vectors);
        let parsed: Vec<BenchRatio> = serde_json::from_str(&meta).expect("round-trip parse");
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].label, "A");
        assert_eq!(parsed[0].enc, Some(0.85));
        assert_eq!(parsed[0].dec, Some(1.1));
        assert_eq!(parsed[1].label, "B;|escape");
        assert_eq!(parsed[1].enc, None);
        assert_eq!(parsed[1].dec, None);
    }

    #[test]
    fn meta_bench_ratios_emitted_in_head() {
        // Confirm the JSON array ends up inside a single-quoted `content=''`
        // attribute on the `<meta name="bench_ratios">` tag so readers can
        // locate + parse it with a single `serde_json::from_str`.
        let opts = Options::default();
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = bench_ok();
        let c = ctx(Banner::Pass, &opts, &q, &t, &a, &b);
        let html = render(&c);
        assert!(html.contains("<meta name=\"bench_ratios\" content='["));
        // The labels appear in the JSON payload (embedded double-quoted).
        assert!(html.contains("SILK NB 8k mono noise"));
        assert!(html.contains("MUSIC 48k stereo"));
    }

    #[test]
    fn ietf_missing_note_renders_when_flag_says_so() {
        let opts = Options::default();
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = bench_ok();
        let c = ReportContext {
            commit_sha: "abc",
            branch: "main",
            version: "0.9.0",
            commit_subject: "subj",
            timestamp: now(),
            banner: Banner::Pass,
            ietf_vectors: IetfVectorProvision {
                status: ProvisionStatus::Unavailable,
                attempted_fetch: true,
                script: Some("tools/fetch_ietf_vectors.sh".into()),
                exit_code: Some(7),
                reason: Some("network unavailable".to_string()),
            },
            ietf_vectors_present: false,
            preflight: crate::preflight::Outcome::inactive(&IetfVectorProvision {
                status: ProvisionStatus::Unavailable,
                attempted_fetch: true,
                script: Some("tools/fetch_ietf_vectors.sh".into()),
                exit_code: Some(7),
                reason: Some("network unavailable".to_string()),
            }),
            options: &opts,
            quality: &q,
            tests: &t,
            fuzz: Box::leak(Box::new(crate::fuzz::Outcome::not_requested())),
            ambisonics: &a,
            bench: &b,
        };
        let html = render(&c);
        assert!(html.contains("IETF vectors unavailable"));
        assert!(html.contains("fetch_ietf_vectors.sh"));
        assert!(html.contains("network unavailable"));
    }

    #[test]
    fn flag_notes_visible_in_header_strip() {
        let opts = Options {
            quick: true,
            skip_coverage: true,
            ..Options::default()
        };
        let q = quality_ok();
        let t = populated_tests();
        let a = ambisonics_ok();
        let b = bench_ok();
        let c = ctx(Banner::Pass, &opts, &q, &t, &a, &b);
        let html = render(&c);
        assert!(html.contains("<code>--quick</code>"));
        assert!(html.contains("<code>--skip-coverage</code>"));
    }
}
